baseURL = 'https://example.org/'
languageCode = 'zh-TW'
title = '暘的世界'
theme = "PaperMo"

[menu]
    [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 10

    [[menu.main]]
    identifier = "tags"
    name = "很多標籤"
    url = "/tags"
    weight = 10

    [[menu.main]]
    identifier = "archievs"
    name = "很多檔案"
    url = "/archives"
    weight = 20